# Generated by Django 3.2.2 on 2021-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='本文')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='投稿時間')),
            ],
        ),
    ]
